plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
future: true
paginate: 25
excerpt_separator: <!--more-->
url: https://blog.marcduiker.nl
title: I ❤️ Serverless, Dev Community, and Creative Coding
author:
  name: Marc Duiker
whitelist:
  - jekyll-redirect-from